### ISSUE TITLE
xml signing

### ISSUE THREAD

**Issue by acerov** [digitalbazaar/forge#241]
Hi thank you for the project, I am still evaluating it for use in my case

I need to sign client side created xml.
Till now I am generating correct DigestValue but having problem with SignatureValue
What is the easiest way to sign xml with x509 certificate

Thank you!

**Comment by mattcollier** [comment]
@acerov, here's the code I'm using for signatures.  Does this help?

**Comment by dlongley** [comment]
> What is the easiest way to sign xml with x509 certificate

Note that an x509 certificate holds a public key; signatures are performed using the private key that is paired with that public key. There are examples for how to sign with an RSA private key here:

https://github.com/digitalbazaar/forge#rsa

Generally, you pick a hash algorithm, generate a message digest object for it, digest what you want to sign (your XML), and then pass the message digest object to a private key object's `sign` method. Then you can base64 or hex-encode the result and put it somewhere to be transmitted.

**Comment by BaurzhanSakhariev** [comment]
I solved the same problem recently. SignatureValue is not as expected because you shouldn't just signing of message digest like  `privateKey.sign(md)' but add to digest some additional data as [described here](http://www.di-mgt.com.au/xmldsig2.html). Note, that description is about **enveloped** signature, if you want to get **enveloping** you have to read [other description](http://www.di-mgt.com.au/xmldsig.html). 

In short, you have to add SignedInfo tag which contains digest algo, signature algo, canonicalization algo. In code it looks like:
```
            var md = forge.md.sha1.create();
			md.update('<content>some content</content>', 'utf8');
			//console.log("xml");
			var messageDigest = forge.util.encode64(md.digest().data); // now you just pki.sign it, it's wrong
			var signedInfoPrefix = '<ds:SignedInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\n';
			var signedInfo = signedInfoPrefix + 
                    '<ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod>\n' +
                    '<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha1"></ds:SignatureMethod>\n' +
                    '<ds:Reference URI="">\n' +
                    '<ds:Transforms>\n' +
                    '<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></ds:Transform>\n' +
                    '<ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments"></ds:Transform>\n' +
                    '</ds:Transforms>\n' +
                    '<ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha1"></ds:DigestMethod>\n' +
                    '<ds:DigestValue>'+messageDigest+'</ds:DigestValue>\n' +
                    '</ds:Reference>\n' +
                    '</ds:SignedInfo>';
			var md = forge.md.sha1.create();
			md.update(signedInfo, 'utf8');
			var signature = privateKey.sign(md);
			console.log(forge.util.encode64(signature));
```
The most important thing to produce correct Signature Value is 3 components: indents, namespaces and specification versions/dates in tags. These components should be the same with reference signed XML produced with Java or other tool even if specification example is different.

For example, my 'reference' of signed xml, contains `ds` prefix before signature related tags, which means simply digital signature namespace. If your reference file doesn't contain ds you should also ignore it. 
Also, my reference signed XML doesn't contain spaces before each tag and I didn't insert 6,8,10 spaces as in description.
Finally, dates and versions should be the same with reference. For example, description provides example with Signature Method = `http://www.w3.org/2000/09/xmldsig#rsa-sha1` but I wrote `http://www.w3.org/2001/04/xmldsig-more#sha1` because my reference XML has that versions.


Finally, you have correct digest value, signature value, the last component is X509 certificate. You may extract cert with the following code:

    var certBags = p12.getBags({bagType: forge.pki.oids.certBag});
    var bag = certBags[forge.pki.oids.certBag][0];
    var cert = bag.cert;
    //console.log(cert);
    var certPEM = forge.pki.certificateToPem(cert);
    certPEM = certPEM.replace('-----BEGIN CERTIFICATE-----', '');
    certPEM = certPEM.replace('-----END CERTIFICATE-----', '');
    console.log(certPEM);

Now you are ready to construct signed XML with Java Script by putting relevant components to according tags and further string concatenation)

**Comment by dlongley** [comment]
@BaurzhanSakhariev,

Hopefully all of this information will be helpful to others, so thank you for that! Does this mean the issue is resolved for you, or do you need anything else?

**Comment by acerov** [comment]
Thank you guys,
I finally got it right and my signed xml is passing verification. Issue closed :)

**Comment by dlongley** [comment]
Great!

**Comment by BaurzhanSakhariev** [comment]
@acerov, could you please tell me, how you canonizing and verifying xml? Do you use xml-crypto library? If yes, how you made it work in browser? Please, PM me to baurzhansahariev@gmail.com

**Comment by acerov** [comment]
BaurzhanSakhariev,
I canonize with https://github.com/deoxxa/xml-c14n
I had to change exclusive-canonicalisation.js because it is writen for server side AFAIK, so I just put:
return cb(null, this._processInner(node));
before setImmediate
I don't use xml-crypto just forge for signing, for verification I use external tool.

**Comment by BaurzhanSakhariev** [comment]
@acerov, thanks!

**Comment by betoharres** [comment]
@dlongley Hello Dave, thanks for help us! I appreciate <3 

Could you elaborate this part you wrote earlier for me? 
> and then pass the message digest object to a private key object's sign method.

I have the same problem as the OP, but I couldn't understand how do I pair a **private key** with the **public key** from the **certificate**. I couldn't find/understand where the `privateKey` is coming from the examples. 

What I've got so far is:
```ES6
let pfxFile = fs.readFileSync('certificate.pfx');
let p12b64 = Buffer(pfxFile).toString('base64');
let p12Der = forge.util.decode64(p12b64);
let p12Asn1 = forge.asn1.fromDer(p12Der);
let p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, 'password');

const certBags = p12.getBags({bagType: forge.pki.oids.certBag});
const bag = certBags[forge.pki.oids.certBag][0];

const cert = bag.cert;
let certPEM = forge.pki.certificateToPem(cert);
certPEM = certPEM.replace('-----BEGIN CERTIFICATE-----', '')
certPEM = certPEM.replace('-----END CERTIFICATE-----', '')
certPEM = certPEM.trim()
```
Now I'm stuck looking the examples trying to figure out, any help?
Note that I'm very new in this subject, hope you understand :)

**Comment by SuperMasterBlasterLaser** [comment]
@BaurzhanSakhariev did you solved this problem. I have also stuck at canonicalization. When I converted this lib  [https://github.com/deoxxa/xml-c14n](https://github.com/deoxxa/xml-c14n) by browserify and called:

    var canon = CanonicalisationFactory.createCanonicaliser("http://www.w3.org/TR/2001/REC-xml-c14n-20010315");

I have also received an error. _CanonicalisationFactory is not defined_ error.
