### ISSUE TITLE
How import forge public key to web crypto?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [digitalbazaar/forge#256]
I'm sorry for asking almost similar question to the previous one but I couldn't resolve it by myself. 

How import forge public key to web crypto? pkcs#8 relevant only for private key, for public keys I may specify "raw" or "spki". I tried stripped and not stripped PEM with importKey("raw"...), no success.  I also tried "raw" and ArrayBuffer(pubKeytoAsn->toDer.getBytes), "spki" and and ArrayBuffer(pubKeytoAsn->toDer.getBytes) and again failed. 

It seems I have to manually construct  JSON parameter in the example below.

    window.crypto.subtle.importKey(
    "jwk", //can be "jwk" (public or private), "spki" (public only), or "pkcs8" (private only)
    {   //this is an example jwk key, other key types are Uint8Array objects
        kty: "RSA",
        e: "AQAB",
        n: "vGO3eU16ag9zRkJ4AK8ZUZrjbtp5xWK0LyFMNT8933evJoHeczexMUzSiXaLrEFSyQZortk81zJH3y41MBO_UFDO_X0crAquNrkjZDrf9Scc5-MdxlWU2Jl7Gc4Z18AC9aNibWVmXhgvHYkEoFdLCFG-2Sq-qIyW4KFkjan05IE",
        alg: "RS256",
        ext: true,
    },

A saw `n` and `e` attributes in forge public key but I didn't understand is JSON 'n' value is base64 of forge key's n-array which has 74 elements?

**Comment by dlongley** [comment]
Use `spki` which stands for "SubjectPublicKeyInfo", the standard ASN.1 structure for serialized public keys. Forge serializes its public keys to this format using `forge.pki.publicKeyToAsn1`.

```js
  var subjectPublicKeyInfo = forge.pki.publicKeyToAsn1(publicKey);
  var der = forge.asn1.toDer(subjectPublicKeyInfo).getBytes();

  console.log('importing public key');
  window.crypto.subtle.importKey(
    'spki', str2ab(der),{
      name: "RSASSA-PKCS1-v1_5",
      hash: {name: "SHA-256"}
    },
    false,
    ['verify']).then(function(result) {
      console.log('imported public key', result);
    }).catch(function(err) {
      console.log('error', err);
    });
```

**Comment by dlongley** [comment]
To clarify further, the `raw` format in the Web Crypto API is just for symmetric keys. Symmetric keys are just opaque blobs of information. Asymmetric keys, on the contrary, are composed of integers that must be serialized in some format so they can be parsed back out later. The popular formats for asymmetric keys are `spki` (ASN.1's SubjectPublicKeyInfo, for public keys) and `pkcs8` (ASN.1's PrivateKeyInfo, for private keys). Web Crypto also supports `jwk` (JSON Web Keys), which is a JSON-serialization of public/private keys instead of an ASN.1 + DER serialization. ASN.1 is an abstract syntax for describing information and DER (Distinguished Encoding Rules) is a concrete syntax for serializing ASN.1 structures to a byte stream.

**Comment by BaurzhanSakhariev** [comment]
Thank you! 

Looks like I was close to solution

> "spki" and and ArrayBuffer(pubKeytoAsn->toDer.getBytes) and again failed

But probably I muddled up some variables during my expiriments) 

Know signing and verifying works as expected. Thanks for collaboration!

**Comment by dlongley** [comment]
Sure! Glad it works. :)
