### ISSUE TITLE
Derive from password

### ISSUE THREAD

**Issue by Canifex** [digitalbazaar/forge#262]
Is it possible to derive a keyset from a password with forge?

**Comment by dlongley** [comment]
By "keyset" do you mean "keypair" (an asymmetric private + public key pairing?)

If so, this provides some good background on why that's a bad idea:

http://crypto.stackexchange.com/questions/1662/how-can-one-securely-generate-an-asymmetric-key-pair-from-a-short-passphrase

So, you can derive a keypair from a password in forge, but it's a bad idea and it will take some custom work. There's nothing built-in to do this for you, because it's generally considered bad practice. You'll need to ensure your PRNG is deterministic and is always seeded the same way. Forge provides a way for you to override these things to do whatever you need them to do, for example, [this test always generates the same keypair by providing a custom PRNG](https://github.com/digitalbazaar/forge/blob/b7510af9f29b1f3faa333dac32b115ba3a213b9c/nodejs/test/rsa.js#L62-L93). At present, forge always uses the same algorithm for finding primes during RSA key generation -- so this will also be deterministic. In the future, we may add more algorithms, but we'll provide a mechanism to select one if you do need a particular one.

**Comment by Canifex** [comment]
Thanks!
