### ISSUE TITLE
Private key from GOST format

### ISSUE THREAD

**Issue by makenti** [digitalbazaar/forge#275]
How to extract private key from certificate in GOST (https://en.wikipedia.org/wiki/GOST_(block_cipher)) format?

**Comment by dlongley** [comment]
You'd have to implement the GOST cipher. Per the wikipedia article, it appears that it is not fully defined by its standard, so even once implemented, you may still find there's an incompatibility with whatever data you're working with.

**Comment by BaurzhanSakhariev** [comment]
I'm also interested in that problem. 

@makenti, do you mean extract GOST private key from pkcs#12 file or something else? 

AFAIK, ASN.1 format is just JSON-like format, i.e sequence-bla-bla-bla, integer:bla-bla-bla, and each algorithm has own structure because even private and public keys are different (GOST~ECDSA, publiv key is point (x,y)). So, you should fork forge project and write own GOST-container parser, looking for forge RSA keys container parser as reference implementartion. 

I really don't understant, why dlongley tells about GOST cipher implementation - probably, some values inside key-certificate container encrypted with GOST. May be I understand your question incorrectly. But if you want to parse key container, rewrite parser, not cipher.

**Comment by makenti** [comment]
hello @BaurzhanSakhariev. thx for your advice. I will write to your email for detail information.

**Comment by dlongley** [comment]
Closing as potentially resolved, also, no plans to implement GOST in forge.

**Comment by alexmironof** [comment]
@dlongley Still no plans to implement GOST? 
I found  https://github.com/rudonick/crypto library, but it is impossible for me to pull another crypto library
