### ISSUE TITLE
secureProtocol equivalent

### ISSUE THREAD

**Issue by magne4000** [digitalbazaar/forge#297]
Is there a way to have a similar behavior as `secureProtocol` of nodejs tls module https://nodejs.org/api/tls.html#tls_tls_connect_options_callback ?

**Comment by dlongley** [comment]
You can specify a `version` key in the options given to `tls.createConnection`:

eg: `version: forge.tls.Versions.TLS_1_0`

However, it doesn't behave the same way `secureProtocol` does; rather it places a limit on the highest TLS version to use. A lower TLS version can still be negotiated for by the server. This option is available to force TLS 1.0 connections instead of the default, which will prefer TLS 1.1 connections. Forge presently only supports TLS 1.0 and 1.1 with 1.2 support in the works. It doesn't support SSL 3.0 at all, so there's no worry that it would use that protocol (which is now considered insecure).

A new option for enforcing a minimum version is likely to be added in the future, see #283.

**Comment by magne4000** [comment]
Thanks, I think that it's sufficient for my need
