### ISSUE TITLE
Is it possible to decrypt a message with Public Key in Forge?

### ISSUE THREAD

**Issue by juradosa** [digitalbazaar/forge#301]
Hi,

im trying to decrypt a message with the public key but it looks like forge doesnt support that or did I overlooked something. The point is that I created a encrypted message with my private key in php and now want to decrypt it with the public key in javascript to get the plaintext. 

Can anybody help me out.

Many thanks in advance

**Comment by mattcollier** [comment]
Hello,

Here are some examples of using an asymmetric key for encryption and
decryption.  Note that the public key is used for encryption and the
private key is used for decryption.

https://github.com/digitalbazaar/forge#rsa

On Wed, Sep 30, 2015 at 2:22 AM, juradosa <notifications@github.com> wrote:

> Hi,
>
> im trying to decrypt a message with the public key but it looks like forge
> doesnt support that or did I overlooked something. The point is that I
> created a encrypted message with my private key in php and now want to
> decrypt it with the public key in javascript.
>
> Can anybody help me out.
>
> Many thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalbazaar/forge/issues/301>.
>



-- 
*Matt Collier*

**Comment by juradosa** [comment]
Hi mattcollier,

I know that actually the public key is used for encryption but the reason why I need to decrypt with the public Key is that I want to be the only one who can create the encrypted text and everyone else can decrypt that text with the public Key. In that case the examples on https://github.com/digitalbazaar/forge#rsa can't help me out. I hope you understand what I try to do.

Thank you for your quick reply.

**Comment by dlongley** [comment]
@juradosa,

Are you sure what you're describing is what you want? The system you've described offers no protection for encrypted messages whatsoever, anyone can decrypt them, so what's the point of encrypting? There is no standardized encryption scheme for such a thing because it offers no security.

Can you provide some more details on what you're trying to do at a higher level? Maybe something else is more appropriate?

**Comment by juradosa** [comment]
@dlongley 

The Idea is that I create a license Key for a Program and the encrypted Text contains Information like the "CompanyName" and because of the containing Information like the CompanyName it can only work at that one Company because their System is labeled with their CompanyName. So even when another company gets that license Key it would not work because their System is labeled different. What I'm trying to avoid is that no one else can create that license Key except me and that's why I choosed this method. 

In OpenSSL it looks like this (encrypting/decrypting)
-generate the Keys
	genrsa -out private.pem 2048 ()
-create the Public Key from the Privat Key
	rsa -in private.pem -pubout -out public.pem
-decrypt the plaintext with Private Key (Sign)
	rsautl -sign -in plaintext.txt -inkey private.pem -out decryptedtext.txt
-encrypt the decryptedtext with Public Key (Verify)
	rsautl -verify -in decrypted.txt -inkey public.pem -pubin -out plaintext.txt

In PHP (encrypting)
	$fp=fopen("private.pem","r");
	$priv_key=fread($fp,filesize("private.pem"));
	openssl_private_encrypt($string,$strEncrypted,$priv_key,OPENSSL_PKCS1_PADDING);
	$base64EncodeString = base64_encode($strEncrypted);
	return $base64EncodeString;

The decrypted Text I get from PHP I want to decrypt in JavaScript. It works already in C++ but now I need it also in JavaScript.

I hope that explaining was on a higher level.

Forgive me for me bad english.
 
Thank you all for helping me out

**Comment by dlongley** [comment]
What you want to do is create a digital signature. Just use the `sign` and `verify` methods listed here instead:

https://github.com/digitalbazaar/forge#rsa

For example:

```js
// load private key from PEM
var privateKey = forge.pki.privateKeyFromPem(privateKeyPem);

// sign data with a private key
// (defaults to RSASSA PKCS#1 v1.5)
var md = forge.md.sha256.create();
md.update('put company name or whatever else in here', 'utf8');
var signature = privateKey.sign(md);
// base64-encode for transport
var signature64 = forge.util.encode64(signature);
```

```js
// load public key from PEM
var publicKey = forge.pki.publicKeyFromPem(publicKeyPem);

// base64-decode signature
var signature = forge.util.decode64(signature64);

// verify data with a public key
// (defaults to RSASSA PKCS#1 v1.5)
var md = forge.md.sha256.create();
md.update('put company name or whatever else in here', 'utf8');
var verified = publicKey.verify(md.digest().bytes(), signature);
// verified is true/false
```

**Comment by juradosa** [comment]
@dlongley,

this example looks like it would just return me true or false. Instead of that I actually want the plaintext to return. 

Another question is that I already have created the encrypted message in PHP without putting an passphrase like 'put company name or whatever else in here' so what should I type in here instead? Nothing " "?

**Comment by mattcollier** [comment]
@juradosa,

A lot of systems have been written to verify that a license has been digitally-signed by an appropriate party, but they follow a standard model for creating and verifying digital signatures -- and forge was written with that model in mind.

The contents of `md` is the 'Message Digest'.  The message digest is a hash (sha256) of the arbitrary text that you would like to digitally sign.  The text could be a JSON, XML, or plaintext that contains the license details.

The request is signed using your private key that only you possess.

On the client side, the signature is verified using the public key which you may distribute along with your software.  The verification function does return true/false.  The the signature validation is true, you can be assured the the message was signed using your private key, and that the message is identical to the original.

Now you may compare the 'System Label' you referred to earlier with license details contained in the signed message with confidence that the license details have not been altered.

A benefit to using a digital signature in this case is that your license data may be any size.  If you attempt to use encryption, the license data must be smaller than the size of the key used to encrypt it.  If you're using 2048 bit RSA keys you'll only be able to store at most 245 characters if you're also using PKCS#1 padding.

**Comment by juradosa** [comment]
My licence Key is not that long so 245 characters is enough. So is it not possible to decrypt a decrypted message with the public Key in Forge? Do you now maybe how I can decrypt this with maybe another library?

**Comment by mattcollier** [comment]
@juradosa 

I think I found the cause of confusion:  http://php.net/manual/en/function.openssl-private-encrypt.php
```
This function can be used e.g. to sign data (or its hash) to prove that it is not written by someone else.
```
In fact you are creating a digital signature with this method.  However, this PHP method is not compatible with forge.  If you would like to sign with PHP in a way that is compatible with forge use: http://php.net/manual/en/function.openssl-sign.php

Be sure to specify the same hashing algorithm for both the sign and verify operations.

**Comment by dlongley** [comment]
@juradosa,

I think the correct path forward is to modify your PHP code to use `openssl_sign` and `openssl_verify` instead.

JFYI, you can decrypt with a public key in forge, but forge doesn't expose a public API for PKCS#1 v1.5 padding decoding in version 0.6.x:

```
var encoded = forge.pki.rsa.decrypt(signature, publicKey, true, false);
```

However, you'd then need to use this private function to remove the PKCS#1 padding:

```
var decoded = _decodePkcs1_v1_5(encoded, publicKey, true);
```
https://github.com/digitalbazaar/forge/blob/master/js/rsa.js#L1424

Again, the proper approach would be to use the right PHP functions and patterns that are intended for doing digital signatures -- because that's the crypto primitive you're working with here.

**Comment by KarthickRathana** [comment]
"If you encrypt with a private key, you can decrypt with a public key." I want this type of code decrypt using public key.

**Comment by dlongley** [comment]
@KarthickRathana,

> "If you encrypt with a private key, you can decrypt with a public key." I want this type of code decrypt using public key.

Why do you want that? A public key by its design is "public". There is an expectation that it is not a secret and that anyone can access and use it. That means that any encrypted data that can be decrypted using a public key isn't worth encrypting. It's not secret. So -- what's your use case? It seems like a different solution is called for.

**Comment by ianbale** [comment]
Why are so many people so reluctant to answer a simple question? Do you really have to know WHY the poster wants to do this? The question was not "What is the best way to do X". If it had been, then your answers may be valid. But, as it is, as far as I can see, every single "answer" posted here is off topic...

Can anyone actually answer the original question?

And I could add, if not with Forge, then can anyone recommend anything else that will do the job? I know node-rsa will do the job. Unfortunately, not the with encoding format that I need.

**Comment by dlongley** [comment]
@ianbale,

> Can anyone actually answer the original question?

I don't think so. That's why more information has been requested. I promise that no one is trying to frustrate you, they are just confused by the question and therefore at a loss for how to properly give the best advice or even a proper answer for that matter.

> Do you really have to know WHY the poster wants to do this?

Yes, because the original question is confusing. Note that a direct answer to how to decrypt with a public key, despite it sounding like it doesn't *actually* answer the question was given here:

https://github.com/digitalbazaar/forge/issues/301#issuecomment-144746103

> I know node-rsa will do the job.

A direct link to raw RSA encryption can be found here:

https://github.com/digitalbazaar/forge/blob/master/lib/rsa.js#L475

A direct link to raw RSA decryption can be found here:

https://github.com/digitalbazaar/forge/blob/master/lib/rsa.js#L530

However, based on the original poster's clarifications, these seem to be *the wrong answers*. Note that they also do not answer @KarthickRathana's question because it does not refer to a "type of code decrypt using public key" that mirrors the concept of public key encryption and private key decryption. That type of decryption does not exist -- hence the confusion about the question.

> Why are so many people so reluctant to answer a simple question?

Another person put it this way: ["If you pedal backwards on a fish, does it go backwards? ... A fish is not a bicycle. Similarly, you cannot use a private key to encrypt a message or a public key to decrypt a message. They don't have the right equipment."](https://cs.stackexchange.com/a/59695)

**Comment by ianbale** [comment]
@dlongley

Actually, it is perfectly possible to encrypt a message with a private key and decrypt it with the public one.  Nothing in the RSA spec says otherwise. And other encryption libraries permit this.

You are quite correct that it does not really offer any secrecy for the message contents since, by definition, the key necessary to decode is now public. What is does do is permit anyone with the public key to confirm that the encoded message originated from the person with the private key.

Yes, yes, I know, signing would be more appropriate. And if the question had been "What's the best way to confirm that a message has originated with the authorised sender" then fair enough, the answers above might be appropriate. But that was not the question. The question was, "does Forge support encryption with the private key and decryption with the public one". A question to which a simple "no" might have suffice. Or even "no, but node-rsa does"...

I am in the same boat as @juradosa, but in my case, not by choice. I am making use of an external service from my application. Rightly, or wrongly, this service mandates that I do exactly what @juradosa asked. Use a private key to encrypt data. The reasoning is simple. There are MANY readers of the data, but only one source. Doing it the other way around encryption myself with the public key and distributing the private key to 1000s of users would be quite silly.

I am sure that signing the data would have been more appropriate, but I was not involved in that decision. The service is already up and running and rolled out nationally.  So, there is no possibility to affect change in that regard now. But, clearly this does actually work. So whether or not you would ever choose to do it this way does not mean no one else should consider it.

Sorry to get a bit arsey. I often find that due to my typical type of client and the type of work I do, I am very often doing quite unusual things or using libraries in unexpected way, pushing the bounds of what other people typically do - quite often, having to make custom modifications to libraries that don't quite do what I need. As a result, I often look for answers to questions that other people think are dumb to ask. It is very frustrating having to describe an entire use case - especially when I am under NDA! - just to get an answer to a question that was perfectly answerable without the use case. I do understand the desire to fully understand what someone is doing in the hope of given them better advice though. And I really appreciate the work that you and others do, firstly by providing these libraries and for supporting them.  There are so many of us who's jobs would be do much harder without them.

**Comment by dlongley** [comment]
@ianbale,

> The question was, "does Forge support encryption with the private key and decryption with the public one". A question to which a simple "no" might have suffice.

Well, more commonly, "encryption" with the private key is referred to as signing, and "decryption" with the public key as "verifying". But there is more to these schemes to make them actually secure (e.g. padding) than just the raw operations. Forge supports both of these operations. As linked above, you can call the raw encrypt and decrypt functions directly if you so desire, but it is important to understand the security  characteristics (or lack thereof). Note that both public and private RSA keys share the same mathematical properties -- so they can obviously be used in the same mathematical operations. However, "encryption" and "decryption" as English terms do not so neatly map to the mathematical operations -- and this leads to confusion (as noted).

So, if you'd like to raise a message M to the power of the public key exponent E and mod it by the modulus N, go right ahead. Similarly, you may do so using the private key exponent D. Again, see the links in [my comment here](https://github.com/digitalbazaar/forge/issues/301#issuecomment-336897597), it will accept either type of key for both. But doing this alone (either way) is not a secure encryption scheme.

>  Use a private key to encrypt data. The reasoning is simple. There are MANY readers of the data, but only one source. Doing it the other way around encryption myself with the public key and distributing the private key to 1000s of users would be quite silly.

Well, that deviates from the intended use of the cryptosystem and I highly recommend you get a security review. I recommend using a pre-shared symmetric key instead. It's simpler and what other people do. If you're going to be encrypting data larger than the modulus (minus whatever padding scheme you figure out how to use with this -- note that this is *very* important) you'll need to use symmetric encryption anyway. In short, it sounds like there's a better solution to your problem and going the other way will likely produce more security theater than security.

> Sorry to get a bit arsey. I often find that due to my typical type of client and the type of work I do, I am very often doing quite unusual things or using libraries in unexpected way, pushing the bounds of what other people typically do - quite often, having to make custom modifications to libraries that don't quite do what I need. As a result, I often look for answers to questions that other people think are dumb to ask. It is very frustrating having to describe an entire use case - especially when I am under NDA! - just to get an answer to a question that was perfectly answerable without the use case. I do understand the desire to fully understand what someone is doing in the hope of given them better advice though. And I really appreciate the work that you and others do, firstly by providing these libraries and for supporting them. There are so many of us who's jobs would be do much harder without them.

No worries. I just want to make sure that the answers or advice I give helps lead people in a better direction -- and in one that will actually solve their problem, not merely give the illusion of a solution or similar.

**Comment by ianbale** [comment]
I hear all that you are saying. But, as I say, the mechanism for distributing this data is already set in stone and in use nationally. I have no option but to live with it... The same, unfortunately, is true of so much that this client does. Muppets in the driving seat most of the time!

**Comment by stocktonchow** [comment]
i face similar problem as juradosa. my tasks require me to verify the pkcs7 signed message with the public key. i have the source file, public key and the signed message. I also don't understand how to retrieve the signature from the pkcs7 signed message in forge and perform verification to compare the hash value between source file and the decrypted signature. can anyone give me a hints? Thank you!

**Comment by ianbale** [comment]
I ended up using node-as https://www.npmjs.com/package/node-rsa
That did permit me to use the keys the wrong way around...
