### ISSUE TITLE
forge.xhr does not support synchronous communication

### ISSUE THREAD

**Issue by xang8848** [digitalbazaar/forge#320]
forge.xhr does not support synchronous communication. only asynchronous communication is implemented.

**Comment by dlongley** [comment]
There's no plan to support synchronous communication with forge's XHR. Synchronous communication on the main thread is deprecated in major browsers and is generally a bad idea. Implementing synchronous behavior with forge's XHR is impossible because there is no other choice than to communicate with the flash layer asychronously.

You should also note that any flash-based features will no longer be supported in the next version of forge as flash is being replaced across the Web with HTML5 alternatives.

**Comment by xang8848** [comment]
thank you!
