### ISSUE TITLE
module doesn't load in react-native

### ISSUE THREAD

**Issue by alinz** [digitalbazaar/forge#325]
Hello Your module doesn't load into react-native. i believe you are using [dynamic require](https://github.com/digitalbazaar/forge/blob/master/js/forge.js#L31) to load modules. Is there any way I can get it to work?

**Comment by ysangkok** [comment]
Try [my fork](https://github.com/ysangkok/forge), it has better support for different module systems.

**Comment by ErkanSen14** [comment]
How do we install your fork rather than the main package?

**Comment by ysangkok** [comment]
If you use npm, you can use `"dependencies": {"node-forge" : "ysangkok/forge"}`

**Comment by jburich** [comment]
Has anybody found a work around for this? I have been trying for 2 days now to encrypt some data. An api sends me a modulus and exponent that I have to then use to encrypt data and send to a different service. On our website we use this library but I cannot get it to work with React Native at all. I've also tried the fork by @ysangkok with no luck. I've even explored alternative libraries like https://github.com/z-hao-wang/react-native-rsa and none of them work. react-native-rsa was the only one I could even get to run, all of the others cause my app to crash, but react-native-rsa does something (I can't figure out what) differently because the service can't decrypt. I know for sure this library works from node for me as I have mocha tests written that call the backend and my code works successfully, but then as soon as I run inside React Native I get an error that says: "SyntaxError ../node_modules/node-forge/js/forge.js: Deleting local variable in strict mode".

**Comment by ysangkok** [comment]
@jburich What is the problem with my fork? Did you see the example projects?

**Comment by jburich** [comment]
With the fork I get an error that it can't find the crypto module.

**Comment by ysangkok** [comment]
@jburich Please file an issue at https://github.com/ysangkok/forge/issues

**Comment by TechBK** [comment]
@ysangkok Plzz, show me example with react-native!!

**Comment by ranjitpandit** [comment]
@jburich were you able to get node-forge work with react native?

**Comment by jburich** [comment]
hmm, I did I got it working but I don't recall how its been so long. When I get into work today I'll take a look at the code and let you know.

**Comment by dlongley** [comment]
Hopefully will be addressed in a new release now that #456 has been merged.

**Comment by davidlehn** [comment]
0.7.0 was released with a new commonjs design and build system which should fix this issue.
