### ISSUE TITLE
forge.util.createBuffer() vs forge.util.ByteBuffer()

### ISSUE THREAD

**Issue by UnsungHero97** [digitalbazaar/forge#352]
Should we be using `forge.util.createBuffer()` or `new forge.util.ByteBuffer()`?

**Comment by dlongley** [comment]
You can use either in forge 0.6.x. `forge.util.createBuffer` allows you to specify `utf8` encoding to convert a regular character string to a forge byte buffer.

In forge 0.7.x, we'll likely prefer `new forge.util.ByteBuffer()` and require an encoding to be specified there if using a string input.

**Comment by UnsungHero97** [comment]
got it, that makes sense. thanks! when will 0.7.x be ready?

**Comment by dlongley** [comment]
> when will 0.7.x be ready?

As soon as possible, but that's a little ways off. Not because there's a whole lot to do, but because I'm the main blocker on getting it finished and I'm swamped with a bunch of other higher-priority projects. Most of the difficult changes for 0.7.x are done, but there are a few API changes we want to fix up before everyone starts using them and we can't go back. We also want to get the library's build system corrected before we do anything else on 0.7.x because it will generate more work if we don't. There are a number of issues related to fixing up the build system -- and some proposed changes that we're evaluating and tweaking.

I wish I could give you a more solid time frame than that, but I can't at the moment.

**Comment by UnsungHero97** [comment]
no worries. thanks for clarifying! good luck!
