### ISSUE TITLE
Some notes about JSEncrypt and its friendly api

### ISSUE THREAD

**Issue by hbrls** [digitalbazaar/forge#365]
The [JSEncrypt](https://github.com/travist/jsencrypt) is somehow straight forward:

```javascript
var publicKey = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDlOJu6TyygqxfWT7eLtGDwajtNFOb9I5XRb6khyfD1Yt3YiCgQWMNW649887VGJiGr/L5i2osbl8C9+WJTeucF+S76xFxdU6jE0NQ+Z+zEdhUTooNRaY5nZiu5PgDB0ED/ZKBUSLKL7eibMxZtMlUDHjm4gwQco1KRMDSmXSMkDwIDAQAB";

var encrypt = new JSEncrypt();
encrypt.setPublicKey(publicKey);
var encrypted = encrypt.encrypt("text to protect");
```

The forge equivalent is:

```javascript
var pkstr = '-----BEGIN PUBLIC KEY-----' + publicKey + '-----END PUBLIC KEY-----'; // not friendly
var pk = forge.pki.publicKeyFromPem(pkstr);
var bytes = pk.encrypt("text to protect"); // `bytes` cost me a night
var encrypted = forge.util.encode64(bytes);
```

Can we have some document warn about that?

And I think #182 and #254 are also trapped by the byte and base64 thing.

**Comment by hbrls** [comment]
And the current document is leading me wrong.

    // encrypt data with a public key (defaults to RSAES PKCS#1 v1.5)
    var encrypted = publicKey.encrypt(bytes);
   // should be =>
    var encryptedInBytes = publicKey.encrypt(normalTextString);

**Comment by dlongley** [comment]
@hbrls,

> // should be =>
var encryptedInBytes = publicKey.encrypt(normalTextString);

This is incorrect. The `encrypt` function does take bytes -- as a binary-encoded string. It just so happens that strings that contain only ASCII characters have the same representation whether they are binary-encoded strings or regular character strings. If you were to put any character that has a character code greater than 255 into your string, it would cause a failure here. In that case, you must wrap the string in a `ByteBuffer` and specify the string encoding as UTF-8. More on this below.

> Can we have some document warn about that?

Forge was originally written before `TypedArray` support existed in most browsers and it used binary-encoded strings to dramatically improve performance over other mechanisms for encoding bytes (eg: as numbers in an array). The next breaking API change to forge includes fixes to address the confusion around various encoding issues. So the answer to this question is that we'll be avoiding this problem entirely with a new version of the forge API.

> The JSEncrypt is somehow straight forward:

The "somehow" is achieved by limiting the usefulness and interoperability of the library. Cryptographic operations should be performed on binary data with helper mechanisms to ease the use of text strings where appropriate. Most of the time you don't want to encrypt text strings using public key encryption, because it's a bad idea. One reason it's a bad idea is because the length of the string (btw, how is the string encoded before it is encrypted, UTF-8? ([answer: yes, but length isn't checked properly](https://github.com/travist/jsencrypt/blob/1a3872346fd71a73f0655570ee281a90dc2f255d/lib/jsbn/rsa.js#L28-L61]?)) will be capped based on the key size and padding method. IMO, an API should not encourage the direct asymmetric encryption of character strings.

Forge's 0.6.x API is flawed in many ways. The chief failing is the confusion around the fact that, because its inputs are of type `String`, people naturally believe regular character strings are expected instead of binary-encoded strings. Again, we plan to address this in a new version of the API (currently planned to land in 0.7.x). However, we believe it's important to construct and work with the correct primitives when writing crypto code -- so while it will be possible to do, it's unlikely we would make changes to encourage people to directly public key encrypt character strings.

There is also power in the simplicity of knowing that every API takes in binary data and outputs binary data. So there are trade offs for adding special flags to APIs to "build in" auto-converting to various popular encodings (hex or base64, for example). We hope, with forge 0.7.x (or wherever our binary data API fixes land) to present an API that is much more clear about what it expects as inputs and what it delivers as output.

So, in all, your criticism regarding the mystery/confusion over encodings is well taken and we're working to address it. However, we won't be moving in the direction of the JSEncrypt API because it is similarly flawed with its own set of surprises, its primitives are too limited and perhaps encourage ill-advised choices, and I don't believe it has the same use cases as forge.

**Comment by hbrls** [comment]
@dlongley, Thanks for you detailed explanation.

I'm working on replacing JSEncrypt with forge. And I feel fine about your api encourages because I can still wrap it for each project.

After reading your comment, I think I misunderstood the string and byte a lot. I have to review the code again before any new ideas.
