### ISSUE TITLE
Invalid Format pki.privateKeyFrom... PKCS#8

### ISSUE THREAD

**Issue by kitkatbaf** [digitalbazaar/forge#371]
Hi,

From what I saw in Forge. It is not possible with Forge to generate a key pair from a passphrase for encryption with RSA_OAEP.
So I used to complement another library to generate a key pair from a passphrase, Virgil-Crypto

var passphrase = "password";
var salt = forge.random.getBytesSync(256);
var key = forge.pkcs5.pbkdf2(password, salt, 40, 16);
var keyPair = VirgilCrypto.generateKeyPair(keyPBKDF2.key,VirgilCrypto.KeysTypesEnum.RSA_2048);
// keyPair.publicKey = "-----BEGIN PUBLIC KEY----- [...] -----END PUBLIC KEY----- "
// keyPair.privateKey = "-----BEGIN ENCRYPTED PRIVATE KEY-----   [...] -----END ENCRYPTED PRIVATE KEY----- "

var publicKey = forge.pki.publicKeyFromPem(keyPair.publicKey); //passed

var privateKey = forge.pki.privateKeyFromPem(keyPair.privateKey); //fail
// Uncaught Error: Could not convert private key from PEM; PEM header type is not "PRIVATE KEY" or "RSA PRIVATE KEY".

 "-----BEGIN ENCRYPTED PRIVATE KEY----- is PKCS#8 format after searching in google but i don't found a function for read my privateKey.

How i can import him to Forge rsa privateKey ? or it's possible to generate key pair from a passphrase for encryption with RSA-OAEP ?

Thank you and sorry for my english.
regards

**Comment by dlongley** [comment]
> It is not possible with Forge to generate a key pair from a passphrase for encryption with RSA_OAEP.

It's non-standard and generally not a good idea to do that. You have to force your random number generator to be strictly deterministic (you cannot use any random entropy from the system) and you have to expose the algorithm it uses (typically an implementation detail that is open to improvement over time) so that you can regenerate the key pair as needed. It's also very likely to reduce the strength of the key. It's better to generate a random key pair and then use that to encrypt a password-generated symmetric key.

http://crypto.stackexchange.com/questions/1662/how-can-one-securely-generate-an-asymmetric-key-pair-from-a-short-passphrase

That being said...

> How i can import him to Forge rsa privateKey ?

You can import a `BEGIN ENCRYPTED PRIVATE KEY` PEM-formatted key using this function:

```js
// decrypts a PEM-formatted, encrypted private key
var privateKey = pki.decryptRsaPrivateKey(pem, 'password');
```
