### ISSUE TITLE
add build folder

### ISSUE THREAD

**Issue by maruilian11** [digitalbazaar/forge#406]
hi, recently we want to add your lib to https://cdnjs.com, could you please consider adding a build folder with built files so that we can use **git auto-update** depending on git tags to grab each released version files for browser.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6190

**Comment by dlongley** [comment]
Hopefully will be addressed in a new release now that #456 has been merged.

**Comment by davidlehn** [comment]
0.7.0 has been released which includes a built `dist/forge.min.js` file.

**Comment by davidlehn** [comment]
Duplicate of https://github.com/digitalbazaar/forge/issues/186.
Also see https://github.com/digitalbazaar/forge/blob/master/README.md#unpkg

**Comment by maruilian11** [comment]
Many thanks!

**Comment by davidlehn** [comment]
Most of the pre 0.7.0 npm packages have everything thrown in them so can probably be used to build bundles.  I don't know how far back that is true.  All the cruft was stripped out in one recent release but the parts needed to build bundles were added back since apparently people used that.

For <0.7.0 the git source of forge-dist is the same as the main forge repo.  For >=0.7.0 the forge-dist repo is just for built bundles and used to support bower and similar systems.  The built files in the node-forge npm package are the same thing.  They both are build with webpack using UMD format so should load in node or browser environments.  Unfortunate choice of "node-forge" for the npm package since it can now be used in other ways, but a bit late to change that now.

It seems like only support for 0.7.0+ is needed going forward and that could just use the npm package.  The bundles were added specifically to make unpkg and cdnjs easier to support.

**Comment by maruilian11** [comment]
thank you for your explaintion :+1:
