### ISSUE TITLE
Get public key from JWK

### ISSUE THREAD

**Issue by tyrsius** [digitalbazaar/forge#444]
I'm pretty sure I am doing something wrong here, but there are no errors and a public key is generated so this might be a legit bug.

I have a JWK, in the format

```
var key = { alg: 'RS256',
      e: --redacted--,
      n: --redacted--,
      kid: 'O9-F3jeJroZZ6pQgBF2pfVGvo4HpVIwfXzxebFCSguI',
      kty: 'RSA',
      use: 'sig' }
```

Calling

```
var pem = forge.pki.publicKeyToPem(key)
```

Returns a string that appears to be valid

```
-----BEGIN PUBLIC KEY-----
MIHIMA0GCSqGSIb3DQ---redacted---
-----END PUBLIC KEY-----
```

But it fails validation with `ssh-keygen`, and it fails to validate a signature that was generated. Am I getting the PEM incorrectly? I am using [this library](https://github.com/brianloveswords/node-jwa) for validation, which works using a different cert (coming from x509). Is this the wrong way to validate an RSA signature?

**Comment by tyrsius** [comment]
[node-jwk-to-pem](https://github.com/Brightspace/node-jwk-to-pem) appears to do exactly what I need to, but I am hoping that this library (which I already depend on) can achieve the same result without adding another dependency.

**Comment by dlongley** [comment]
The `forge.pki.publicKeyToPem` call uses `e` and `n` parameters on a key object to generate its output, but it assumes the key is in a different format than is being provided here. A longer term solution is to also support JWK input, but right now, the method expects a forge public key object. To solve your problem, I think you need to do something like this:

```js
function base64urlToBigInteger(str) {
  var bytes = forge.util.decode64(
    (str + '==='.slice((str.length + 3) % 4))
      .replace(/\-/g, '+')
      .replace(/_/g, '/'));
  return new forge.jsbn.BigInteger(forge.util.bytesToHex(bytes), 16);
};

var publicKey = forge.pki.setRsaPublicKey(
  base64urlToBigInteger(key.n),
  base64urlToBigInteger(key.e));

var pem = forge.pki.publicKeyToPem(publicKey);
```

**Comment by tyrsius** [comment]
That works, thank you *so much*!! I wish I understood what it was you where doing with that first function, or even how to start unpacking it.

**Comment by dlongley** [comment]
Sure!

The JOSE (JWK/JWT/JWS/etc) stack uses a variant of base64 encoding that is "URL safe". You can't safely put `+` or `/` in a URL, so they replace those characters with `-` and `_`, respectively. That first function just puts them back to the standard base64 chars and then runs a base64 decoding function to get a binary-encoded string. Also, since base64 encoding also uses `=` as a padding char, the function also ensures that the base64 string is a multiple of 4 (base64 encoding works with groups of 3 bytes and effectively bloats them to 4) by adding any needed padding `=` chars.

The byte string is then read in as BigInteger -- which is what the `setRsaPublicKey` function is expecting for the modulus (`n`) and the exponent (`e`).

**Comment by tyrsius** [comment]
Man, I can't thank you enough for the insight. Do you have a git-tip or anything?

**Comment by dlongley** [comment]
> Man, I can't thank you enough for the insight. Do you have a git-tip or anything?

Sure :). I don't have a git-tip, but feel free to donate to the forge project via paypal if you'd like: paypal@digitalbazaar.com.

**Comment by dlongley** [comment]
Thanks @tyrsius!

**Comment by tyrsius** [comment]
Thank you 😃

**Comment by mm-gmbd** [comment]
@dlongley - thanks for the code snippet and the explanation here. Any plans on adding JWK format support to forge? Would love a `jwkToPublicKey` method :smile:
