### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by nigampatel** [digitalbazaar/forge#467]
When are you planning on cutting a new version?  It seems like you have browserify issue resolved in master branch but no version has been cut for it?

**Comment by davidlehn** [comment]
In the next few days.  It would be helpful if people could test and provide feedback on the master branch.  Check for general functionality and test that new things like browserify and webpack support are working as needed.  There were a lot of changes and we've had very limited testing feedback.

**Comment by alexlamsl** [comment]
An issue with my use case is I only need `pkbdf2()` to use within web browsers.

In the current published version I can just package `hmac.js`, `pbkdf2.js`, `sha256.js` and `util.js` together and things will just work.

With the latest version, due to those new `require('md')` etc., I will end up with needing to import a lot more source files, e.g. `sha512.js`, in order to achieve the same functionality.

**Comment by davidlehn** [comment]
@alexlamsl: Good point.  I created a new issue for that and will try to make the require()s less aggressive to allow easier custom builds.

**Comment by nigampatel** [comment]
I just stated looking at this and first thing I notice that when I require('node-forge') it added 275KB of javascript to my browserify bundle.  That is a big file, I would agree with @alexlamsl to make this browser friendly. 

@dlongley thank for creating the new issues to cover this.

**Comment by davidlehn** [comment]
@nigampatel: Yes, the main build is large.  It's actually slightly smaller now than it was before due to removal of some redundant boilerplate and other minor things.  One goal of this next release is to minimize disruption for previous users so that default build will likely stay large.  But the new setup should make custom builds much easier.  And hopefully we can reduce dependencies and so on to make custom builds even smaller.

**Comment by joeheyming** [comment]
When is the due date?

**Comment by davidlehn** [comment]
0.7.0 released.
