### ISSUE TITLE
forge.pkcs5.pbkdf2 produces different derivedKey  for the same password and salt in Windows and iOS browsers

### ISSUE THREAD

**Issue by sidMnair** [digitalbazaar/forge#491]
Hi, 
I'm trying to create an encoded password for my app, but the code that gets generated in Chrome browser (Windows OS) for the same password is different in Safari browser (iOS).

I'm using the below logic:  

```js
var salt = '458aec7c-2397-acc0-94ef-10qcgc49bc39';
var password ='Abc@1234';
var derivedKey = forge.pkcs5.pbkdf2(password, salt, 10000, 128);
var encoded = forge.util.encode64(derivedKey);
```

It produces different derivedKey for the same password and salt. 
Shouldn't it be the same in all the browsers irrespective of the OS ?
Has anyone been able to solve this issue in forge?

**Comment by davidlehn** [comment]
What version of forge?  Please make sure you are using 0.6.45 or later.

There was a webkit optimization bug in safari which forge uncovered and sounds like what you describe.  We added a workaround in forge and the bug was reported and fixed in webkit.
See https://github.com/digitalbazaar/forge/issues/428.

If it's something else, please let us know.

**Comment by sidMnair** [comment]
I was using an older version 0.6.21 and after you suggested I updated it to 0.7.0 and now it works fine.
@davidlehn Thanks alot for the solution.
