### ISSUE TITLE
Non-deterministic behavior with decrypt function (different keys for encrypt and decrypt)

### ISSUE THREAD

**Issue by robertomlsoares** [digitalbazaar/forge#546]
I've been trying to test the modules of my application that encrypt and decrypt my information and realized that the results of the tests are non-deterministic. So I decided to isolate the test to outside of my app so I could share it with you and maybe you can try to reproduce it.

You can put the sample below in an html file and serve it with any basic server just to run the test, or run the fiddle itself with your console open. Notice that sometimes the decrypt function will decrypt the information without having any errors and sometimes it will have errors. Essentially, I want to test what happens if I encrypt something with key X and decrypt it with key Y. Sometimes the library returns the result of `cipher.finish()` as `false` and sometimes as `true`. I want to know which behavior I should expect from this scenario so I can use it in my test.

Option 1: It always returns true but the resulting output is an empty string or some random string, but not the original and correct string that was encrypted.
Option 2: It always returns false because it's not possible to decipher with a different key.

Currently, both cases are happening. Shouldn't it be just one?

Fiddle: https://jsfiddle.net/6ne6ufq4/

**Comment by dlongley** [comment]
The decryption process doesn't know what the original data was, so it can only check validity based on its packaging (i.e. padding). Since a key simply performs mathematical transforms on the data, it's possible for the output to randomly conform to the padding requirements -- hence, no validity error is raised despite the fact that the decrypted output does not match the original encrypted input. In most applications the decrypted data itself would fail validation as an application-specific check post decryption.

**Comment by robertomlsoares** [comment]
Hey, thanks for answering!

Sorry, I think I didn't understand it that well. I'm not saying that the decrypt function from the library itself should check that the data is the same as the original data before encryption, since as you said, this process doesn't have access to that. But take a look at the fiddle, I'm encrypting and decrypting stuff with the same parameters (same iv, etc) and only changing the key. What should happen at this point? Two different things are happening.

_In most applications the decrypted data itself would fail validation as an application-specific check post decryption._
That's basically my test, I want to check that the output of the `decrypt(encrypt())` operation (each function using different keys) is different from the plaintext because the keys are different. An attacker shouldn't have access to the plaintext if he has the ciphertext but uses the wrong key in the decryption process, right? The `decipher.finish()` sometimes returns `true` and sometimes `false`.

Since I don't have such a good grasp on the inner workings of cryptography, let me put it this way: when you run that fiddle, why sometimes the `decipher.finish()` returns both `true` and `false` with nothing changing? The only thing that changes in that test is the IV that is random, but the same IV is used both for encryption and decryption, so I don't think that's the problem (correct me if I'm wrong, tho).

**Comment by MaxFichtelmann** [comment]
When using a non-authenticated ciphermode like CBC, the engine can not be certain if the output is plausible.

Imagine a padding, where a 0xBC byte is appended for verification reasons
```
const data = 0xAABBCC
const plain = decrypt(key, encrypt(key, pad(data))) // 0xAABBCCBC
```
since the resulting plaintext ends in BC, the engine assumes the plaintext to be recovered. But a different key could result in the same valid padding!
```
const data = 0xAABBCC
const plain = decrypt(wrong_key, encrypt(key, pad(data))) // 0x1452FDBC
```
Just from inspecting the padding, the result looks fine.

To make sure your decrypted data actually matches what was originally encrypted you should use an authenticated mode like AES-GCM. I have updated your sample to use GCM in https://jsfiddle.net/yx4n1njh/1/ (basically change the mode string and use the tag from the encryption cipher output for the decryption cipher initialization)

**Comment by robertomlsoares** [comment]
Hey, @MaxFichtelmann! Thanks for answering. I'm starting to understand now, but just a few more questions...

When you say **key** and **wrong_key,** do you mean the IV that is used here `decipher.start({ iv: iv })` or do you mean the key that is used here `forge.cipher.createDecipher('AES-CBC', key)`? Because the key used in the createCipher and createDecipher calls are always the same, so it should still be deterministic.
If you mean the IV, then I understand the problem now. Since the IV is random, sometimes it's going to happen what you described.

The other question is: if I always use the same key for encryption and decryption, I won't reach the scenario that you described, right? Also, it seems to me (from reading your comment and quickly googling about CBC vs GCM) that GCM is better than CBC since it provides what CBC does + integrity. Would it be wise to just go ahead and change it to CBC or am I missing something and GCM is not always the best choice? I know silver bullets don't exist, but perhaps there is a consensus on this matter?

Thanks a lot!

**Comment by dlongley** [comment]
@robertomlsoares,

> Would it be wise to just go ahead and change it to CBC or am I missing something and GCM is not always the best choice? I know silver bullets don't exist, but perhaps there is a consensus on this matter?

Always use GCM over CBC unless you've got a really good reason for doing otherwise (e.g. you need it for compatibility reasons and there's nothing you can do about changing that).

**Comment by MaxFichtelmann** [comment]
I agree, the only reason for using CBC should be legacy systems.
I used `key` and `wrong_key` to show that using a different key to decipher data may result in a plaintext, that looks ok from the engines perspective since it has limited knowledge, what 'ok' actually means.
A key is very different from an iv. The key is the component, that has to be kept secret. An IV is used to avoid encrypting different plain text blocks with the same key input, which leaks information about the secret key.

It is perfectly ok to send iv and tag along the encrypted message in plain, do not try to keep them secret - they are not meant to be.

**Comment by robertomlsoares** [comment]
Thanks a lot, everyone. Will use GCM from now on.

But still, I'm curious about the different keys problem. I'm using the same different pair of keys on every test. Even though they're different keys, every run of the test should have the same behavior, no?

Run 1: Run test with key X to encrypt and key Y to decrypt. `decipher.finish()` returns `true`.
Run 33: Run test with key X to encrypt and key Y to decrypt. `decipher.finish()` returns `false`.

If I understood correctly, if what @MaxFichtelmann described in his first comment happens here, it should happen on every run of the test. Unless, and that's where my doubt is, the random IV sometimes causes the ciphertext to have the padding problem. Could it be?

**Comment by MaxFichtelmann** [comment]
yes, the random iv is the reason for that behaviour. the ciphertext is different whenever you use a different iv. Therefore the decryption result is completely different each time, when using a key that differs from the encryption key.

**Comment by robertomlsoares** [comment]
Thank you very much for your patience, @MaxFichtelmann and @dlongley! :)

Btw, feel free to close the issue.

**Comment by dlongley** [comment]
@robertomlsoares, sure! :)
