### ISSUE TITLE
How to take certificate from p12 file without '-----BEGIN CERTIFICATE -----' headers

### ISSUE THREAD

**Issue by ghari18** [digitalbazaar/forge#588]
I am able to read certificate in pem format 
`cert = certBags[forge.pki.oids.certBag][0];
certPem = forge.pki.certificateToPem(cert.cert);`

But the result is 
`--------- BEGIN CERTIFICATE ----------
MIIEodhdjhggbnbbvghvhbbjhdhbJkkjjbjnnn ... 
--------- END CERTIFICATE -----------`

How can i take certificate string alone without the header and trailer in NodeJS

**Comment by davidlehn** [comment]
You want to read a cert without the header and footer?  Or you want to write one?  If reading, maybe easiest to just add the header and footer.  If trying to write, maybe easiest to just strip it out afterwards.  Otherwise, you can look at the x509.js certificateToPem code, and see how it uses the pem.js code, and make some direct calls that do what you want.

**Comment by ghari18** [comment]
Actually i got the solution
`cert = certBags[forge.pki.oids.certBag][0]; 
certPem = forge.pki.certificateToPem(cert.cert);
certDer = forge.pki.pemToDer(certPem);
p12b64 = forge.util.encode64(certDer.data);`

Converting pem to der and doing base64 encoding. This will remove the header and footer of the certificate
