### ISSUE TITLE
Different seeds generate the same RSA using PRNG!

### ISSUE THREAD

**Issue by LancerZC** [digitalbazaar/forge#794]
I try to restore our RSA using PRNG, but I found it's insecure, different seeds can generate the same RSA. 

After looking at the source code, found that in prng.js, it will use the return value of seedFileSync to fill the 32 pools, which are MD actually.
```js
ctx.collect(ctx.seedFileSync(needed));
```

If take a look at the collect() function, it just copy one char to each pool.
```js
 ctx.collect = function(bytes) {
    // iterate over pools distributing entropy cyclically
    var count = bytes.length;
    for(var i = 0; i < count; ++i) {
      ctx.pools[ctx.pool].update(bytes.substr(i, 1));
      ctx.pool = (ctx.pool === 31) ? 0 : ctx.pool + 1;
    }
  };
```

When generating the seed, I found that this line `md.update(ctx.pools[k].digest().getBytes());` was only executed once!
```js
    // digest the entropy of pools whose index k meet the
    // condition 'n mod 2^k == 0' where n is the number of reseeds
    var _2powK = 1;
    for(var k = 0; k < 32; ++k) {
      if(ctx.reseeds % _2powK === 0) {
        md.update(ctx.pools[k].digest().getBytes());
        ctx.pools[k].start();
      }
      _2powK = _2powK << 1;
    }
```

That means only 1st char was used to generate seed each time! And I found those code was execute twice for generating one RSA, that means only 2 chars was used.!

We can easily reproduce the problem. Run below code, the public key are exactly the same. The seeds was made by me.
```js
const forge = require('node-forge');

function getPubKey(seed) {
    let prng = forge.random.createInstance();
    prng.seedFileSync = function (needed) {
        return seed;
    };
    let keyPair = forge.rsa.generateKeyPair(512, { prng: prng });
    return forge.pki.publicKeyToPem(keyPair.publicKey);
}

console.log(getPubKey('abc1d345345435'))
console.log(getPubKey('abcdsjdjsdkjflsd'))
```

Yes, I saw that in many examples codes, we can use padding (forge.util.fillString) to avoid this, because in ctx.collect(), it will repeat fill the pools. But we still found that, it will generate the same RSA in certain scenario (because only 1st and 2nd pools are used!), I use forge.random.getBytes(32) to generate  hundreds of thousands seed (not much, right?), then found duplicated RSA.
```html
<script src="dist/forge.js"></script>
<script>
    function getPubKey(seed) {
    let prng = forge.random.createInstance();
    prng.seedFileSync = function (needed) {
        return forge.util.fillString(seed,needed);
    };
    let keyPair = forge.rsa.generateKeyPair(512, { prng: prng });
    return forge.pki.publicKeyToPem(keyPair.publicKey);
}

console.log(getPubKey(atob('wAK5cyBL4tj+F2Blpq7cGmeWdo1U+4/JLunQPEiYmBk=')))
console.log(getPubKey(atob('wAIocx/W607p0JCi6I8qZik8gm8R4wDcYp7i+OwXiVs=')))
</script>
```
So I think the PRNG is insecure, there is a bug there, before we have fix, we should not use it in production.

**Comment by dlongley** [comment]
The seed file API is such that the function will be called with a `needed` parameter indicating how many random bytes are required. The use of the API in your examples will not provide that many random bytes when using `forge.util.fillString`, instead, it repeats the same 32 bytes `needed` times in a row.

Internally, the expected random bytes will be distributed amongst 32 pools to fill them -- according to the Fortuna PRNG spec. Each pool digests the random bytes using SHA-256. Then, based on the number of reseeds that have occurred so far in the generator, specific pools will be selected to provide bytes to create a key for encrypting an internal incrementing number, again, per the Fortuna spec.

Since the seed files in the examples above always use the same two characters in the same location ('ab' or 'wA', respectively) and they repeat themselves on 32 byte boundaries per the use of `fillString` and the parameters given to it, they are not clearly not providing random data. These same two bytes will be the only inputs to the PRNG -- and hence, you'll get the same output out of the generator. If you want different output, you must provide the `needed` number of random bytes in the `seedFileSync` function you implement. The default seed file will use the browser's built in secure PRNG and so it should not suffer from this problem.

If this is clear, please go ahead and close the issue. Thanks!

**Comment by LancerZC** [comment]
Thanks for prompt response!
When I debug the program, the `needed` is 1024, and the return type of `seedFileSync` is string, so I need to return string with length 1024? It's so large string! It's not reasonable to use string with length 1024 to generate unique RSA!

Can we convert the random string to bits, and return a string with bits, to generate unique RSA?
e.g. random string is "abc", and bits of "abc" is `011000010110001001100011,` we return `011000010110001001100011` (string) instead of `abc` in seedFileSync() , is that ok?
Or simply ask like this, can we return a random string with just "0" or "1" , but its length is `needed` in `seedFileSync` , to generate unique RSA?

**Comment by andywer** [comment]
@LancerZC You can use a simple key derivation function like HKDF ([here](https://www.npmjs.com/package/futoin-hkdf) is a node package) to stretch your seed to the required length to seed the PRNG. Just make sure that the seed is not too short (256 bit should be fine).

**Comment by LancerZC** [comment]
Great, thanks a lot for your advice 👍
