### ISSUE TITLE
[Security issue] Publish the unminified dist files to npm

### ISSUE THREAD

**Issue by limonte** [digitalbazaar/forge#814]
Hey, maintainers! I don't trust you. But don't worry it's not personal. I don't trust anyone on the Internet.

But my suspicion to `node-forge` can be less if you guys publish the unminified dist files to npm. With the unminified files your users can actually check and verify what they're using.

Currently there are only minified files: https://www.jsdelivr.com/package/npm/node-forge?path=dist

![image](https://user-images.githubusercontent.com/6059356/92119525-97a7f900-ee00-11ea-9c68-71c569217341.png)

Please publish the unminified files (`forge.all.js`, `forge.js`, `prime.worker.js`) to the `dist` folder.

Thank you.

--

PS. Here's the related reading: https://medium.com/hackernoon/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

> **I’d see it in your source on GitHub!**
>
> Your innocence warms my heart.
> 
> But I’m afraid it’s perfectly possible to ship one version of your code to GitHub and a different version to npm.
> 
> In my package.json I’ve defined the files property to point to a lib directory that contains the minified, uglified nasty code — this is what npm publish will send to npm. But lib is in my .gitignore so it never makes its way to GitHub. This is a pretty common practice so it doesn’t even look suspect if you read through these files on GitHub.
> 
> This is not an npm problem, even if I’m not delivering different code to npm and GitHub, who’s to say that what you see in /lib/package.min.js is the real result of minifying /src/package.js?
> 
> So no, you won’t find my nasty code anywhere on GitHub.

**Comment by davidlehn** [comment]
The [Security Considerations](https://github.com/digitalbazaar/forge#security-considerations) section of the README tries to cover issues related to this.  The installation section refers to it too.  I think we didn't distribute those bundled files at all early on.  But they are useful for `<script>` use cases.  If you're using webpack, or a similar bundler, then your (hopefully trusted) toolchain will use the plain source files rather than the minified ones.  I think it was a practical consideration to only include minified files, since any bundled files are not likely used in the common application level bundler situation, and they would just add another ~2M of often useless files to the package.

In your use case I'm guessing you specifically want to use pre-bundled files?  If the large unminified files were included, you would still have to trust that the webpack process made them properly.  For online use cases you would also want to minify them yourself, which means trusting a minifier.

There are many possible attacks on the toolchain, no matter who runs it.  There is also always a risk of just a regular obfuscated code attacks as well.  I'm not sure how to tradeoff these types of concerns with convenience of pre-bundled code.  I'd like to hear more about the use case before adding extra bloat to the package size.

**Comment by limonte** [comment]
> 
> 
> The [Security Considerations](https://github.com/digitalbazaar/forge#security-considerations) section of the README tries to cover issues related to this. The installation section refers to it too. I think we didn't distribute those bundled files at all early on. But they are useful for `<script>` use cases. If you're using webpack, or a similar bundler, then your (hopefully trusted) toolchain will use the plain source files rather than the minified ones. I think it was a practical consideration to only include minified files, since any bundled files are not likely used in the common application level bundler situation, and they would just add another ~2M of often useless files to the package.

It seems like your only consern in this case is the diskspace on npmjs servers. It is valid, but IMO should have less priority than security and trust from users who don't (or can't) use webpack in their projects.

> In your use case I'm guessing you specifically want to use pre-bundled files? If the large unminified files were included, you would still have to trust that the webpack process made them properly. For online use cases you would also want to minify them yourself, which means trusting a minifier.

In our case we're using good old `<script>`, not webpack. Webpack is popular, but not mandatory to be present in toolchains :)

> There are many possible attacks on the toolchain, no matter who runs it. There is also always a risk of just a regular obfuscated code attacks as well. I'm not sure how to tradeoff these types of concerns with convenience of pre-bundled code. I'd like to hear more about the use case before adding extra bloat to the package size.

All possible attacks on the toolchain are irrelevant for people who prefer **security** and **simplicity** and use`<script>` and unminified bundles.

**Comment by wiktor-k** [comment]
My 2 cents: regardless of if this is a security issue or not some scenarios like browser extensions require source code that does not use `eval`s (due to strict CSP settings; so `mode: 'production'`) and the source code should *not* be minified (so `{ optimization: { minimize: false } }`).

Currently `webpack.config.js` does not generate such files but it did so in version 0.9.1 of node-forge that we previously used (previously the "development" version did not use `eval`s).

Do you think it would be a useful addition @davidlehn? I could provide a PR if we could agree on a way to proceed.
