### ISSUE TITLE
HMAC-SHA256 output 

### ISSUE THREAD

**Issue by imknight** [digitalbazaar/forge#917]
I need the output to be in base64, but not sure how do it.

I manage to generate the plain text format, but wonder how to do the base64 output like  using this tool https://www.devglan.com/online-tools/hmac-sha256-online 

md.start('sha256','123');
md.update('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.MTIz','utf8');

**Comment by bfricka** [comment]
Come on man, this isn't stack overflow. The maintainers need to work on core issues rather than teach you how to convert to base64.

Anyways, I'll answer you so it shows up on search:

```ts
const h = forge.hmac.create()
h.start('sha256', '123')
h.update('whatever')
const byteBuffer = h.digest()
// "hex" is the "plain text" value described on the site
const hex = byteBuffer.toHex(); // '6e286e47aade83ad3740a8bc83ef183ca69feb23e702ebe64add250760b30a62'
```
To get the "base64" output referred to by that site you need to convert bytes to base64. You can do this natively in node or use the utilities provided by forge.

```ts
// Using forge
const byteString = byteBuffer.bytes()
const base64 = forge.util.encode64(byteString); // 'bihuR6reg603QKi8g+8YPKaf6yPnAuvmSt0lB2CzCmI='

// Using node
const buffer = Buffer.from(byteBuffer.toHex(), 'hex');
const base64 = buffer.toString('base64'); // 'bihuR6reg603QKi8g+8YPKaf6yPnAuvmSt0lB2CzCmI='
```
